# Fold information
fold: 0

# Training/Testing details
w_ms: 0.0
w_ce: 1.0
batch_classes: 16
batch_samples: 16
ds: 1
device: "cuda"
degrade_precision: False
seq_len: 300
map_at_r: False
batch_size_for_testing: 256
epochs: 100

# Eval
n_seq: 1
round: 1
task: "TEX"
bootstrap: False
val: False
plot: False
protocol_file: "src.evaluate.protocols.gazecapture"


#Dirs
log_dir: "./logs"
ckpt_dir: "./output/del/gazecapture"
embed_dir: "./embeddings/del/gazecapture"
model_name: "del_t5000_ds1_bc16_bs16_wms10_wce01_normal"
plot_dir: "./figures"

model_file: "src.models.del-gazecapture"