dataset_config: "config/dataset/gazebase.yaml"  
model_config: "config/model/ekyt.yaml"         
metadata: "Model presented in Lohr'22 study, Eye Know You Too: Toward Viable End-to-End Eye Movement Biometrics for User Authentication operated on GazeBase Dataset"
