dataset_config: "config/dataset/gazebase.yaml"  
model_config: "config/model/del-gazebase.yaml"         
metadata: "Model presented in Machowsky '20 study: Biometric Identification and Presentation-Attack Detection using Micro- and Macro-Movements of the Eyes"