dataset_dir: "./data/gazecapture"
raw_dir: "./data/gazecapture/raw"
processed_dir: "./data/gazecapture/processed"
dataset_file: "src.data.gazecapture.dataset"
downsample_factors: 1
initial_sampling_rate_hz: 60
n_folds: 4
num_workers: 1
cache_size: 8000000000 #8GB