dataset_dir: "./data/gazebasevr"
raw_dir: "./data/gazebasevr/raw"
processed_dir: "./data/gazebasevr/processed"
dataset_file: "src.data.gazebasevr.dataset"
downsample_factors: 1
initial_sampling_rate_hz: 250
n_folds: 4
num_workers: 1
cache_size: 8000000000 #8GB